flat-kernel: add option for build only kernel image
Signed-off-by: Dede Dindin Qudsy <xtrymind@gmail.com>

diff --git a/flat-kernel b/flat-kernel
--- a/flat-kernel
+++ b/flat-kernel
@@ -10,7 +10,7 @@
 source ${HOME}/dotfiles/common
 
 # directory
-KERNELDIR=${HOME}/devel/kernel
+KERNELDIR=${HOME}/local/kernel
 SOURCE_FOLDER=${KERNELDIR}/mido
 OUT_FOLDER=${SOURCE_FOLDER}/out
 BIN_FOLDER=${HOME}/bin
@@ -54,6 +54,10 @@ function parse_parameters() {
                 shift && enforce_value "${@}"
 
                 DEFCONFIG=${1} ;;
+
+            # Do not package kernel image
+            "-io"|"--image-only")
+                IMAGE_ONLY=true ;;
 
             # Where to move zip after compilation
             "-m"|"--mode")
@@ -110,7 +114,7 @@ function device_flags() {
             DEVICE_NAME_FILE=${DEVICE^}
             DEVICE_NAME_GITHUB=mido
 
-            [[ -z ${GCC_FOLDER} ]] && GCC_FOLDER=${TC_FOLDER}/aarch64-linux-gnu_8.2.1
+            [[ -z ${GCC_FOLDER} ]] && GCC_FOLDER=${TC_FOLDER}/aarch64-linux-gnu_8.x
             [[ -z ${CLANG_FOLDER} ]]&& CLANG_FOLDER=${TC_FOLDER}/android-clang-8.x/
             ;;
 
@@ -206,8 +210,8 @@ function build_kernel() {
     fi
 
     # Make the kernel
-    #kmake 2>&1 | tee ../kernel.log
-    kmake
+    kmake 2>&1 | tee ../kernel.log
+    #kmake
 
     # Find the compiled files
     OUT_KERNEL_IMAGE=$(find "${OUT_FOLDER}/arch/${ARCHITECTURE}" -name 'Image.*-dtb' 2>/dev/null)
@@ -224,11 +228,20 @@ function build_kernel() {
 
 # Move kernel files after compilation
 function move_kernel_files() {
+    if [[ -z ${IMAGE_ONLY} ]]; then
         # Move the kernel image
         cp "${OUT_KERNEL_IMAGE}" "${ANYKERNEL2_FOLDER}"
         [[ -n ${OUT_DTBO_IMAGE} ]] && cp "${OUT_DTBO_IMAGE}" "${ANYKERNEL2_FOLDER}/dtbo"
         echo "Kernel version: $(cat "${OUT_FOLDER}/include/config/kernel.release")" >> "${ANYKERNEL2_FOLDER}/version"
         echo "Revision: $(cat "${OUT_FOLDER}/.version")" >> "${ANYKERNEL2_FOLDER}/version"
+    fi
+}
+
+# After build tasks
+function after_build_tasks() {
+    if [[ -z ${IMAGE_ONLY} ]]; then
+        package_zip
+    fi
 }
 
 # Package zip
@@ -254,17 +267,20 @@ function package_zip() {
     else
         echo "${GRN}Kernel zip successfully generated!${RST}\n"
         rm "${UNSIGNED_ZIP}"
-        echo "${GRN}Kernel located at ${PWD}/${SIGNED_ZIP} ${RST}\n"
+        cp "${SIGNED_ZIP}" "${HOME}/flatKernel"
+        echo "${GRN}Kernel located at ${HOME}/flatKernel/${SIGNED_ZIP} ${RST}\n"
         echo "Time elapsed: $(format_time "${START}" "$(date +"%s")")"
     fi
 }
 
 # Clean up
 function clean_up() {
-    # Clean AnyKernel2 folder
-    cd "${ANYKERNEL2_FOLDER}" || die "AnyKernel2 source is missing!"
-    echo "Cleaning at ${PWD}"
-    git clean -xfd
+    # Clean AnyKernel2 folder if building a zip
+	if [[ -z ${IMAGE_ONLY} ]]; then
+		cd "${ANYKERNEL2_FOLDER}" || die "AnyKernel2 source is missing!"
+		echo "Cleaning at ${PWD}"
+		git clean -xfd
+    fi
 
     # enter kernel directory
     cd "${SOURCE_FOLDER}" || die "Kernel source is missing!"
@@ -346,11 +362,20 @@ function generate_changelog() {
 
 
 header "COMPILING KERNEL"
+
+# Parse command line parameters and setup options
 parse_parameters "${@}"
 device_flags
 generate_variables
+
+# Clean up the source
 clean_up
+
 # Generate variables such as versions
 generate_version
+
+# Build kernel
 build_kernel
-package_zip
+
+# After build tasks
+after_build_tasks
