merge-stable: change ALS folder
Signed-off-by: Dede Dindin Qudsy <xtrymind@gmail.com>

diff --git a/merge-stable b/merge-stable
--- a/merge-stable
+++ b/merge-stable
@@ -239,11 +239,11 @@ function generate_versions() {
         )
 
         echo "\n${BOLD}Fetching stable-queue...${RST}\n"
-        STABLE_QUEUE=${ALS:?}/stable-queue
+        STABLE_QUEUE=${KERNEL_FOLDER:?}/stable-queue
         if [[ -d ${STABLE_QUEUE} ]]; then
             git -C "${STABLE_QUEUE}" pull &>/dev/null || die "Error pulling stable queue!"
         else
-            git -C "${ALS}" clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git &>/dev/null || die "Error cloning stable queue!"
+            git -C "${KERNEL_FOLDER}" clone git://git.kernel.org/pub/scm/linux/kernel/git/stable/stable-queue.git &>/dev/null || die "Error cloning stable queue!"
         fi
 
         echo "${BOLD}Generating ${QUEUE_BRANCH}...${RST}"
